development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: riat
  suffix: development
  username: test	
  password:	test

test:
  <<: *development
  suffix: test

production:
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: praxeng2
  suffix: development
  username: test
  password: test
